### ISSUE TITLE
Wrong highlighting when the return type is generic

### ISSUE THREAD

**Issue by laicasaane** [needle-tools/demystify#1]
![demystify](https://user-images.githubusercontent.com/1594982/109633890-34164280-7b7b-11eb-8f65-605edd5b35c9.png)
![demystify](https://user-images.githubusercontent.com/1594982/109634201-8bb4ae00-7b7b-11eb-8de4-f3dd0e8529a0.png)

**Comment by marwie** [comment]
Thanks for the report!
Could you send a screenshot of your settings as well (Edit/Preferences Needle/Demystify) and also copy paste some example code that is not correctly highlighted?

**Comment by marwie** [comment]
should be fixed in the next update

Before:
![image](https://user-images.githubusercontent.com/5083203/109817077-c6791d80-7c31-11eb-81ae-2429d55b2624.png)
![image](https://user-images.githubusercontent.com/5083203/109817273-06400500-7c32-11eb-859a-57758f89b0bf.png)


After: 
![image](https://user-images.githubusercontent.com/5083203/109817168-e4df1900-7c31-11eb-91f8-5621a881550c.png)
![image](https://user-images.githubusercontent.com/5083203/109817189-eb6d9080-7c31-11eb-8297-d820bbbba9df.png)

**Comment by marwie** [comment]
@laicasaane fixed in 1.0.1-pre.6
